import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { ThemeProviders } from "./theme-provider";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Providers from "./provider";

const inter = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <AppRouterCacheProvider options={{ key: "css" }}>
            <ThemeProviders>
              {children}
              <Toaster />
            </ThemeProviders>
          </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  );
}
